# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(default=None)),
                ('hash', models.CharField(blank=True, default=None, max_length=64)),
                ('path', models.CharField(help_text='File path', max_length=512)),
                ('imported_from_path', models.CharField(help_text='File path as was before import, for history', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('myfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.MyFile')),
            ],
            bases=('files.myfile',),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('myfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.MyFile')),
            ],
            bases=('files.myfile',),
        ),
    ]
