# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='created',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='imported_from_path',
            field=models.CharField(blank=True, help_text='File path as was before import, for history', max_length=512),
        ),
    ]
