# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20160830_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='created',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
