# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20160831_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='myfile',
            name='imprt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.Imprt'),
            preserve_default=False,
        ),
    ]
