# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20160831_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
