# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20160831_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfile',
            old_name='imported',
            new_name='imported_date',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='created',
        ),
        migrations.AddField(
            model_name='myfile',
            name='created_date',
            field=models.DateTimeField(default=None, help_text='Date from file metadata', null=True),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='hash',
            field=models.CharField(db_index=True, help_text='Unique file identifier', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='imprt',
            field=models.ForeignKey(help_text='All files from one import have same imprt object', on_delete=django.db.models.deletion.CASCADE, to='files.Imprt'),
        ),
    ]
