# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20160831_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='created_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Date from file metadata', null=True),
        ),
    ]
