# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20160906_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='imprt',
            field=models.ForeignKey(help_text='All files from one import have same imprt object', on_delete=django.db.models.deletion.CASCADE, related_name='myfiles', to='files.Imprt'),
        ),
    ]
