# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20160906_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='thumb',
            field=models.CharField(blank=True, default=None, help_text='Thumb path', max_length=512, null=True),
        ),
    ]
