# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_myfile_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfile',
            old_name='thumb',
            new_name='_thumb',
        ),
    ]
