# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20161103_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPhoto',
            fields=[
                ('myfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.MyFile')),
            ],
            bases=('files.myfile',),
        ),
    ]
