# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_rawphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='_preview',
            field=models.CharField(blank=True, default=None, help_text='Preview path', max_length=512, null=True),
        ),
    ]
